name: Create Release Binaries

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag for this release (e.g., v0.4.4)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.0"

      - name: Get tag name
        id: get_tag
        run: echo "TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT

      - name: Verify version in package.json matches release tag
        run: |
          # Extract version without the 'v' prefix
          VERSION=$(echo "${{ steps.get_tag.outputs.TAG }}" | sed 's/^v//')
          
          # Check if desktop/package.json version matches
          CURRENT_VERSION=$(node -p "require('./desktop/package.json').version")
          
          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            echo "::error::Version mismatch: package.json version ($CURRENT_VERSION) does not match release tag version ($VERSION)"
            echo "Please update the version in desktop/package.json to match the release tag."
            exit 1
          else
            echo "Version in package.json ($CURRENT_VERSION) matches release tag"
          fi

      - name: Install dependencies (web)
        run: |
          cd web
          npm install

      - name: Install dependencies (desktop)
        run: |
          cd desktop
          npm install

      - name: Build web app
        run: |
          cd web
          npm run build
          
      - name: Setup for building
        run: |
          cd desktop
          mkdir -p ./dist/2dTaskBoard
          cp -r ../web/dist/* ./dist/2dTaskBoard/

      - name: Build Linux AppImage
        run: |
          cd desktop
          npx electron-builder --linux AppImage

      - name: Install Wine for Windows build
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine wine32 wine64 mono-complete

      - name: Build Windows exe
        run: |
          cd desktop
          npx electron-builder --windows nsis --x64
      
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            desktop/release-builds/*.AppImage
            desktop/release-builds/*.exe
          tag_name: ${{ steps.get_tag.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
